# Generated by Django 4.1.5 on 2024-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading', models.CharField(default='', max_length=500)),
                ('subheading1', models.CharField(default='', max_length=500)),
                ('subheading2', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='tourpackage/images')),
            ],
        ),
    ]
