# Generated by Django 4.1.5 on 2024-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='', upload_to='tourpackage/images'),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
