# Generated by Django 4.1.5 on 2024-11-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0002_package_category_package_image_package_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('peraddress', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip', models.IntegerField(max_length=6)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
