# Generated by Django 4.1.5 on 2024-11-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0004_booking_alter_contact_phone_alter_contact_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='traveller',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
