# Generated by Django 4.1.5 on 2024-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0005_booking_traveller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='traveller',
            new_name='inputTraveller',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='request',
        ),
        migrations.AddField(
            model_name='booking',
            name='textarea',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
