# Generated by Django 4.1.5 on 2024-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0006_rename_traveller_booking_inputtraveller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='inputTraveller',
            field=models.CharField(default='', max_length=10),
        ),
    ]
