# Generated by Django 4.1.5 on 2024-11-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0007_alter_booking_inputtraveller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='items_json',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='inputTraveller',
            field=models.CharField(max_length=10),
        ),
    ]
