# Generated by Django 4.1.5 on 2024-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0008_remove_booking_items_json_booking_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(default='')),
                ('destination', models.CharField(max_length=50)),
                ('day_plan', models.IntegerField(default='')),
                ('day_0', models.CharField(max_length=20)),
                ('day_1', models.CharField(max_length=20)),
                ('day_2', models.CharField(max_length=20)),
                ('day_3', models.CharField(max_length=20)),
                ('day_4', models.CharField(max_length=20)),
                ('day_5', models.CharField(max_length=20)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
