# Generated by Django 4.1.5 on 2024-11-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0009_bookingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_0',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_1',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_2',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_3',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_4',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_5',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='day_plan',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='destination',
        ),
    ]
