# Generated by Django 4.1.5 on 2024-11-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0010_remove_booking_destination_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
