# Generated by Django 4.1.5 on 2024-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0011_delete_bookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='textarea',
            field=models.CharField(max_length=1000),
        ),
    ]
